### ISSUE TITLE
Possible for open files to expand and scroll with the rest of the sidebar?

### ISSUE THREAD

**Issue by isGabe** [postcasio/tree-view-open-files#33]
The space for open files appears to be a fixed height, which scrolls once more file are open than will fit in that vertical space. For me this almost defeats the purpose,as I have to hunt for open files.

Honestly what I really am looking for is just how ST does it. Having open files is one of those little features that is a deal maker/breaker for me.

**Comment by maprihoda** [comment]
+1 for ST-like functionality, they have it implemented correctly

**Comment by Instagit** [comment]
max-height for the element is set to 250px. For a workaround, add this to your _styles.less_:

``` css
.tree-view-open-files {
  max-height: none !important;
  overflow: visible;
}
```

It should do exactly what you want.
