### ISSUE TITLE
Not working in new Atom v1.6 update

### ISSUE THREAD

**Issue by luckyshot** [postcasio/tree-view-open-files#38]
The Pane doesn't load open tabs anymore in the new Atom v1.6 update

**Comment by luckyshot** [comment]
Commenting this CSS property solved the issue for me:

`.tree-view-open-files {
    /* overflow: auto; */
}`

**Comment by MadLittleMods** [comment]
Seems to be working in Atom 1.6.2 and shows a few files.

This fix works great for showing all of them (will cut-off if you have more open tabs than vertical space on your screen for your tree-view). Inspired by https://github.com/bloopletech/config/commit/33431dff6f0616fa639d118bf2d466572a2bc1e8, could be more releated to https://github.com/postcasio/tree-view-open-files/issues/33

``` css
.tree-view-open-files {
  overflow: visible !important;
  max-height: 30vh !important;

  transition: max-height 0.2s ease;

  &:hover {
    max-height: 100vh !important;
  }
 }
```
